apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: edushare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: edushare
type: Opaque
stringData:
  POSTGRES_DB: edushare
  POSTGRES_USER: edushare_user
  POSTGRES_PASSWORD: edushare_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: edushare
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "edushare_user", "-d", "edushare"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "edushare_user", "-d", "edushare"]
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: edushare
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
