apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: shareschool-kargo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: shareschool-dev
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promo-process-dev
          as: promo-process-dev