apiVersion: v1
kind: Secret
metadata:
  name: ghcr-cred
  namespace: shareschool-kargo
  labels:
    kargo.akuity.io/cred-type: image
type: Opaque
stringData:
  repoURL: ghcr.io/sa8aa/shareschool
  username: sa8aa
  password: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: shareschool-repo
  namespace: shareschool-kargo
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: https://github.com/sa8aa/shareskooll.git
  username: sa8aa
  password: ""