apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: shareschool-dev
  namespace: shareschool-kargo
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/sa8aa/shareschool 
        imageSelectionStrategy: NewestBuild
        allowTags: "^dev-[a-f0-9]{8}$"
        discoveryLimit: 5
        strictSemvers: false

    - git:
        repoURL: https://github.com/sa8aa/shareskooll.git
        branch: dev
        includePaths:
          - manifests/k8s
          - manifests/kargo