name: CI
on:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  sonarqube:
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit

  frontend:
    needs: sonarqube
    uses: ./.github/workflows/frontend.yml
    secrets: inherit

  trivy-frontend:
    needs: frontend
    uses: ./.github/workflows/trivy.yml
    with:
      service: frontend
      image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:${{ github.sha }}
      report-name: trivy-frontend-report
    secrets: inherit

  backend:
    needs: trivy-frontend
    uses: ./.github/workflows/backend.yml
    secrets: inherit

  trivy-backend:
    needs: backend
    uses: ./.github/workflows/trivy.yml
    with:
      service: backend
      image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-backend:${{ github.sha }}
      report-name: trivy-backend-report
    secrets: inherit
